<?xml version="1.0" encoding="UTF-8"?>
<Layout version="1.6.1">
  <Mode>Vertical</Mode>
  <X>1</X>
  <Y>105</Y>
  <VerticalWidth>368</VerticalWidth>
  <VerticalHeight>772</VerticalHeight>
  <HorizontalWidth>-1</HorizontalWidth>
  <HorizontalHeight>-1</HorizontalHeight>
  <Settings>
    <TextColor>FFFFFFFF</TextColor>
    <BackgroundColor>FF0F0F0F</BackgroundColor>
    <BackgroundColor2>00000000</BackgroundColor2>
    <ThinSeparatorsColor>03FFFFFF</ThinSeparatorsColor>
    <SeparatorsColor>24FFFFFF</SeparatorsColor>
    <PersonalBestColor>FF16A6FF</PersonalBestColor>
    <AheadGainingTimeColor>FF00CC36</AheadGainingTimeColor>
    <AheadLosingTimeColor>FF52CC73</AheadLosingTimeColor>
    <BehindGainingTimeColor>FFCC5C52</BehindGainingTimeColor>
    <BehindLosingTimeColor>FFCC1200</BehindLosingTimeColor>
    <BestSegmentColor>FFD8AF1F</BestSegmentColor>
    <UseRainbowColor>True</UseRainbowColor>
    <NotRunningColor>FFACACAC</NotRunningColor>
    <PausedColor>FF7A7A7A</PausedColor>
    <TextOutlineColor>00000000</TextOutlineColor>
    <ShadowsColor>80000000</ShadowsColor>
    <TimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAA1Db21pYyBTYW5zIE1TAABAQQX8////GFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQEAAAAHdmFsdWVfXwAIAgAAAAEAAAAF+////xtTeXN0ZW0uRHJhd2luZy5HcmFwaGljc1VuaXQBAAAAB3ZhbHVlX18ACAIAAAACAAAACw==]]></TimesFont>
    <TimerFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAA1Db21pYyBTYW5zIE1TAAAvQgX8////GFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQEAAAAHdmFsdWVfXwAIAgAAAAEAAAAF+////xtTeXN0ZW0uRHJhd2luZy5HcmFwaGljc1VuaXQBAAAAB3ZhbHVlX18ACAIAAAACAAAACw==]]></TimerFont>
    <TextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAA1Db21pYyBTYW5zIE1TAABAQQX8////GFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQEAAAAHdmFsdWVfXwAIAgAAAAEAAAAF+////xtTeXN0ZW0uRHJhd2luZy5HcmFwaGljc1VuaXQBAAAAB3ZhbHVlX18ACAIAAAACAAAACw==]]></TextFont>
    <AlwaysOnTop>True</AlwaysOnTop>
    <ShowBestSegments>True</ShowBestSegments>
    <AntiAliasing>False</AntiAliasing>
    <DropShadows>True</DropShadows>
    <BackgroundType>Image</BackgroundType>
    <BackgroundImage><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABVTeXN0ZW0uRHJhd2luZy5CaXRtYXABAAAABERhdGEHAgIAAAAJAwAAAA8DAAAAfCQAAAKJUE5HDQoaCgAAAA1JSERSAAAAyAAAAJIIAgAAAI8vElgAAAAEZ0FNQQAAsY58+1GTAAAAIGNIUk0AAIcPAACMDwAA/VIAAIFAAAB9eQAA6YsAADzlAAAZzHM8hXcAAAo1aUNDUHNSR0IgSUVDNjE5NjYtMi4xAABIx52Wd1RU1xaHz713eqHNMNIZepMuMID0LiAdBFEYZgYYygDDDE1siKhARBERAUWQoIABo6FIrIhiISioYA9IEFBiMIqoqGRG1kp8eXnv5eX3x73f2mfvc/fZe5+1LgAkTx8uLwWWAiCZJ+AHejjTV4VH0LH9AAZ4gAGmADBZ6am+Qe7BQCQvNxd6usgJ/IveDAFI/L5l6OlPp4P/T9KsVL4AAMhfxOZsTjpLxPkiTsoUpIrtMyKmxiSKGUaJmS9KUMRyYo5b5KWffRbZUczsZB5bxOKcU9nJbDH3iHh7hpAjYsRHxAUZXE6miG+LWDNJmMwV8VtxbDKHmQ4AiiS2CziseBGbiJjEDw50EfFyAHCkuC845gsWcLIE4kO5pKRm87lx8QK6LkuPbmptzaB7cjKTOAKBoT+Tlcjks+kuKcmpTF42AItn/iwZcW3poiJbmlpbWhqaGZl+Uaj/uvg3Je7tIr0K+NwziNb3h+2v/FLqAGDMimqz6w9bzH4AOrYCIHf/D5vmIQAkRX1rv/HFeWjieYkXCFJtjI0zMzONuByWkbigv+t/OvwNffE9I/F2v5eH7sqJZQqTBHRx3VgpSSlCPj09lcni0A3/PMT/OPCv81gayInl8Dk8UUSoaMq4vDhRu3lsroCbwqNzef+pif8w7E9anGuRKPWfADXKCEjdoALk5z6AohABEnlQ3PXf++aDDwXimxemOrE4958F/fuucIn4kc6N+xznEhhMZwn5GYtr4msJ0IAAJAEVyAMVoAF0gSEwA1bAFjgCN7AC+IFgEA7WAhaIB8mADzJBLtgMCkAR2AX2gkpQA+pBI2gBJ0AHOA0ugMvgOrgJ7oAHYASMg+dgBrwB8xAEYSEyRIHkIVVICzKAzCAGZA+5QT5QIBQORUNxEA8SQrnQFqgIKoUqoVqoEfoWOgVdgK5CA9A9aBSagn6F3sMITIKpsDKsDRvDDNgJ9oaD4TVwHJwG58D58E64Aq6Dj8Ht8AX4OnwHHoGfw7MIQIgIDVFDDBEG4oL4IRFILMJHNiCFSDlSh7QgXUgvcgsZQaaRdygMioKiowxRtihPVAiKhUpDbUAVoypRR1HtqB7ULdQoagb1CU1GK6EN0DZoL/QqdBw6E12ALkc3oNvQl9B30OPoNxgMhobRwVhhPDHhmATMOkwx5gCmFXMeM4AZw8xisVh5rAHWDuuHZWIF2ALsfuwx7DnsIHYc+xZHxKnizHDuuAgcD5eHK8c14c7iBnETuHm8FF4Lb4P3w7Px2fgSfD2+C38DP46fJ0gTdAh2hGBCAmEzoYLQQrhEeEh4RSQS1YnWxAAil7iJWEE8TrxCHCW+I8mQ9EkupEiSkLSTdIR0nnSP9IpMJmuTHckRZAF5J7mRfJH8mPxWgiJhJOElwZbYKFEl0S4xKPFCEi+pJekkuVYyR7Jc8qTkDclpKbyUtpSLFFNqg1SV1CmpYalZaYq0qbSfdLJ0sXST9FXpSRmsjLaMmwxbJl/msMxFmTEKQtGguFBYlC2UesolyjgVQ9WhelETqEXUb6j91BlZGdllsqGyWbJVsmdkR2gITZvmRUuildBO0IZo75coL3FawlmyY0nLksElc3KKco5yHLlCuVa5O3Lv5enybvKJ8rvlO+QfKaAU9BUCFDIVDipcUphWpCraKrIUCxVPKN5XgpX0lQKV1ikdVupTmlVWUfZQTlXer3xReVqFpuKokqBSpnJWZUqVomqvylUtUz2n+owuS3eiJ9Er6D30GTUlNU81oVqtWr/avLqOeoh6nnqr+iMNggZDI1ajTKNbY0ZTVdNXM1ezWfO+Fl6LoRWvtU+rV2tOW0c7THubdof2pI6cjpdOjk6zzkNdsq6Dbppune5tPYweQy9R74DeTX1Y30I/Xr9K/4YBbGBpwDU4YDCwFL3Ueilvad3SYUOSoZNhhmGz4agRzcjHKM+ow+iFsaZxhPFu417jTyYWJkkm9SYPTGVMV5jmmXaZ/mqmb8YyqzK7bU42dzffaN5p/nKZwTLOsoPL7lpQLHwttll0W3y0tLLkW7ZYTllpWkVbVVsNM6gMf0Yx44o12trZeqP1aet3NpY2ApsTNr/YGtom2jbZTi7XWc5ZXr98zE7djmlXazdiT7ePtj9kP+Kg5sB0qHN44qjhyHZscJxw0nNKcDrm9MLZxJnv3OY852Ljst7lvCvi6uFa6NrvJuMW4lbp9thd3T3Ovdl9xsPCY53HeU+0p7fnbs9hL2Uvllej18wKqxXrV/R4k7yDvCu9n/jo+/B9unxh3xW+e3wfrtRayVvZ4Qf8vPz2+D3y1/FP8/8+ABPgH1AV8DTQNDA3sDeIEhQV1BT0Jtg5uCT4QYhuiDCkO1QyNDK0MXQuzDWsNGxklfGq9auuhyuEc8M7I7ARoRENEbOr3VbvXT0eaRFZEDm0RmdN1pqraxXWJq09EyUZxYw6GY2ODotuiv7A9GPWMWdjvGKqY2ZYLqx9rOdsR3YZe4pjxynlTMTaxZbGTsbZxe2Jm4p3iC+Pn+a6cCu5LxM8E2oS5hL9Eo8kLiSFJbUm45Kjk0/xZHiJvJ4UlZSslIFUg9SC1JE0m7S9aTN8b35DOpS+Jr1TQBX9TPUJdYVbhaMZ9hlVGW8zQzNPZkln8bL6svWzd2RP5LjnfL0OtY61rjtXLXdz7uh6p/W1G6ANMRu6N2pszN84vslj09HNhM2Jm3/IM8krzXu9JWxLV75y/qb8sa0eW5sLJAr4BcPbbLfVbEdt527v32G+Y/+OT4XswmtFJkXlRR+KWcXXvjL9quKrhZ2xO/tLLEsO7sLs4u0a2u2w+2ipdGlO6dge3z3tZfSywrLXe6P2Xi1fVl6zj7BPuG+kwqeic7/m/l37P1TGV96pcq5qrVaq3lE9d4B9YPCg48GWGuWaopr3h7iH7tZ61LbXadeVH8Yczjj8tD60vvdrxteNDQoNRQ0fj/COjBwNPNrTaNXY2KTUVNIMNwubp45FHrv5jes3nS2GLbWttNai4+C48Pizb6O/HTrhfaL7JONky3da31W3UdoK26H27PaZjviOkc7wzoFTK051d9l2tX1v9P2R02qnq87Inik5Szibf3bhXM652fOp56cvxF0Y647qfnBx1cXbPQE9/Ze8L1257H75Yq9T77krdldOX7W5euoa41rHdcvr7X0WfW0/WPzQ1m/Z337D6kbnTeubXQPLB84OOgxeuOV66/Jtr9vX76y8MzAUMnR3OHJ45C777uS9pHsv72fcn3+w6SH6YeEjqUflj5Ue1/2o92PriOXImVHX0b4nQU8ejLHGnv+U/tOH8fyn5KflE6oTjZNmk6en3KduPlv9bPx56vP56YKfpX+ufqH74rtfHH/pm1k1M/6S/3Lh1+JX8q+OvF72unvWf/bxm+Q383OFb+XfHn3HeNf7Puz9xHzmB+yHio96H7s+eX96uJC8sPAb94Tz+zq4vlMAAAAJcEhZcwAACwwAAAsMAT9AIsgAABmxSURBVHhe7d15VBPX/gDwJISEZBISAoSIAqK4FKu4UMW11lpBwUREFi22wYcrYCsi1qJIcYPaylr1KWhbUcljkSJoscGyBURbgRbltMcFGhaRAoFsECHzOy/3OS8OENvf6ztP4H6Of+DcO3dyTr5ncucu3yEQIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIOgvNH369KCgoM2bNwcatHnz5qCgoOnTp+PPhyCMmZnZ/PnzFy9e7OzsLBKJ0D9MJBI5OzsvXrx4/vz5ZmZm+HahUc7Dw6OhoaG1tbWpqUmpVOLDZ2hKpbKpqam1tbWhocHDwwPfLjQ6IQgSHx//5MmTtrY2fMj8eW1tbU+ePImPj0cQBH8laFQ5depUQ0MDPkD+Mw0NDadOncJfCRolmExmUFAQPij+OkFBQUwmE39VaGSztbWNiIjAx8JfLSIiwtbWFn9taAQ7cuRId3c3PhD+at3d3UeOHMFfGxqpiERifHw8Pgr+O+Lj44lEIv4TQCOPiYlJQEBAXV0dPgT+O+rq6gICAkxMTPCfAxphmExmXl4e/vv/b8rLy4O9+JEPQZCMjAzcd19fXy8Wi4uKioqfKyoqkkgkWq0WVxOj1WolEkmRzvfPicXi+vp6XM2MjAw4rDXy4QILhM7+/fstLCy4L7K3t5fJZC/EiB6ZTGZvb8/lcs3NzNgIAv5x2Gb79+/HmgVgYI0K+oHV3t4+e/ZsBwcHOp2Or6fj6OhYUFDw72h6rqCgwNHREdR53d837P794Pt3Qm5X8t6YTaPRHBwcZs+e3d7eDirDwBoVsMCqqakRCoX44hdRqdSBv5sgVijGxgQCYV6gMKy26gSKxqPocbRvW7F44srl4FyhUFhTUwMDa7TAAisrK4tEIuGLX8RgMLKysvBhhaJZmZkMhOEStGPfg/unUPTDuh9XnzoRpXqagKIhkqLJy94iGpOJBAI4FwbWqMBgMLKzs1EUzc3NpVAo+OIX0en0zMxMfFihaIZIhDAYOyrLo5UdiSgq/CbTaubrEe0Nx1BNbFf7ms+Pk2gmxiRSbm4uiqLZ2dkMBgPfNDTCIAgCllvl5+e/9EbCYrFAFGq12j4d0CvPzs42ZTLp1tz3cjLiUDS6pyvqacthrfwzFF0VH0Om0cCF8vPzwYKtl14IGvZIJBKPx0tNTVUqlbdv3yaRSEONjDMYjOrqarlcDnrrr+uAvrxcoaiuqqIZGyOWloLEhNMomoyi8T2qeTu3U03/OWRFIpFu376tVCpTU1N5PN5Lf3OhEeLEiRPgRy0tLS09Pf2dd97B1yAQyGSySqUC1a5evUrUuXr1KjiiUqnIRkYEAoHtYD/FZ+3ENR4TV7kTiIS3lixJT09PS0sD1U6cOIFvFxrBfH19y8rK+vv7wdefnZ3t7e393nvv7dixIyQkZNKkScbGxgEBASCw6urqQkJCjHVCQkLAdJBKpQoICKBQKPY2Npv81gt9fL1WrVq7Zk32lSugzf7+/rKyMl9fX/y1oZHNxcUFuyFhamtr7969u2fPnuDgYOzg7t279U/cvXs3VhQcHLxnz56q6up79+9jBwGVSuXi4qJ/IjQq8Pl8tVoNgqBfRyaT8Xg8IpEYHR0tl8ux0fOoqCj9E6OiosBxrVYrl8ujo6OJRCKPx5PJZKAdUKpWq/l8vv6J0MgXFhYmlUqx0ImIiFi/fr1Coaiqqrp9+zY2aA589NFH+ud+9NFH+qXt7e2VlZVVVVVyuXzdunVgSgeEnVQqDQsL0z8XGuGwzjuwa9cuAoHg7e2tfxBTVVWVkpLylU5KSkpVVRW+ho5Wq122bJmFhcW5c+ewg7DzPrrExsaiKNrT0/P3v//90qVL7u7uXC7X3d39yy+/PHv27J9drdXY2Hj+/Plz587NmTOHQCDY29vHxcX19PSgKBobG4u/NjSCgTtWR0eHk5PTnDlzEATx9PRUq9UEAoHH4x08ePDGjRtisbi4uLiwsPC7774rLCwsKir67rnCwsLi4mLwt1gsjouLmz17NmjZ2tp66dKlM2fO7OjogHesUefYsWPgZtPR0SGXy4VC4ZIlS3755RcWi5WTk3P06FEwn8PhcGg0GoPBMDEx4XA4dB0EQWg0GofDQRCETqdTqdT333+/sbHR3NwcPDN2d3eDqEJR9NixY/hrQyMYj8cLDg7u7e0FX39LS8vJkyenTp3KYDBu3rzZ1tZWWlpaUFBAoVAOHTpUUVFx6NAhGo0mFovLy8vBfykUSkFBQUVFhZ+f38qVK7Va7dixY2NjY7GNr729vcHBwTweD39taGRzc3Pr6+v7Vy8JRZ88eZKQkEAkEsePHw/mbbRaLZvNBhPJubm5FhYW2LhXbm4um80GO/E//fRTY2NjHx+fCxcuPH36FGuwr6/Pzc0NTO9wOBwLHSqViv8c0LBGoVCYOgiCGOmmYmbNmoVL/tHT0xMYGLh06dKdO3deuHDhs88+Y7FY169fR1H02rVrlpaWz549AzWvXbvG4XCUSmVFRcWKFStoNJpAIMBGxQCRSDRr1iwjIyMfHx+pVCrXiYmJIZPJ+A8HDV++vr5ZOhcvXnz99dex48XFxQPXHycnJzs6Ok6dOpVKpUZHRxcVFUVFRSEIkpubKxaLb968efDgQTqdLhKJfHx8nJ2dsSFTQCaTlZSUgPYXL15cXV2NDZip1eoDBw7QdMsfoOHN2NjYz8/vwYMH2BdfVFQ0c+ZMUGptbS0SibRabW9vL/b1q1Sqp0+f1tfXczgcKpVqampqooPoMJlMExMTY2NjKyurzMzM33//HQzTY42IRCLQtfLx8amsrMSum56eHhoaKhAIXroODBoGTExMBu73SktLmzVrFqgwduxYZ2fn0NBQ/S4X8PPPP1dUVJSWlt66dauqqkoikZSVlYH/3r1799atWwqFAqvc19cXGhrq7Ow8btw4kBeptrYWK8rLy5s8eTKHw5k2bRr+I0LDjpGRkZ2dnUgk6ujo6Ozs7OrqwuKgsLBwzJgxpqamoKalpaWvr6+/vz+fz7927RpW7aWuXbvG5/P9/f19fX0tLS1BawiCYFNGWq320aNHNjY2BAIhPDw8Pz/f2tr6hU8JDTv29vatra2bNm0ik8kMBmPKlCnt7e2gH63RaJRKpVQq9fHxAd15zNq1a3Nyci5fvnzJoMuXL+fk5Kxdu1b/XBDNbDYbDGX19fWJRCIskohEYmBgYGNjo6OjI1z9N4wxGAxPT09wtwDPhh4eHt7e3p6enmBWR6vVVldXv/XWW/gz/wPTp0/PyMgAj5DFxcVOTk76i1Q3btyIouiNGzfs7OxeOA0aGczNzQ8dOgR+zqqrqwfeeBAE+fjjj+3t7XHHly5dumXLlkFHpLy8vI4ePYp16TIyMubOnYurM3ny5MOHD4NF9ytWrMCVQsMAl8t1dXU18AhGJBLT09NFIlFbW9uvv/7q5+e3atUqbKzcwsICTPatXLlS8Jybm1thYeGdO3ewzhlAIpE8PT3vP1/u19/fn5OTg21qNTY2dnNz0+9anT9/HkXR1NTUfzcBDQsmJibr16+/e/euhYUFdpBEIrFYLGPdXlOAphMdHa1Wq5VKZWdn55YtW0xNTalUKoIgjY2Nvb29Cj3d3d1qtTotLQ0kkKHRaGydCRMmPH36tKenRyaTdXd319fXjxs3DvSiyGTyhAkTampq3N3dseuamprevHnz3LlzBuIeeuVQKJSUlJTy8nIul6vfv7GxsWlsbFy3bt0LtXU2bNjQoyOTyXp6ei5dumRmZsbj8a5cuYJLDRIbG0skEhkMBpfLvXjxolqt7tZpb2/fsGEDjUZjsVj697N169Y1NTXNmDED11sHE5FXr16FuWiGjaNHjyYlJS1duhS3tWv8+PEKheLdd9/VPwjw+fynT5+uX7/ew8MjOztbLpeLxWIGg+Hk5IQbfdi/f/+UKVMKCgry8vLAoqvS0lJ/f//Vq1dzuVx8uwSCv7+/QqEYNGdkZGQkiqIXL16E8zyvOnNz88jIyNTU1DfeeANfRiDY2dl1dXVt2LABX0AgeHp6NjY2gr+PHDnS0tISFxcHfu+mTJmya9eukJCQnTt37t+/f968eZMmTUpMTERR9KuvviosLLxy5Qq+OT0CgUAmk40fPx5fQCA4OzuDqD158uTApwToFfLaa6+hKOrt7Y0v0DEcWM3NzeDVEqdOnSorKwPHXVxc3N3dFyxYsGjRorlz5+qPeLW0tDg6OgYHB1dUVAy1id7W1vaLL77o7OzEhjxwZsyYARZQ6PfAoFcLiUSaNWtWY2Oj4cAadK8fn89vaWlxcHBgMBjnz58vLy+nUCggg4hSqZTL5QqFoq2t7b333jMyMiKRSHZ2dq2tra6urlFRUSUlJYMGFplMjoiI6O/vb2trs7KywhfrkEgkLpf78OFDPz8//acK6BWyYsWK2traiRMn4kbSMXZ2djKZTCgUgp31CIIwdBAEEQgECoWio6OjtbW1t7cXpAyh0Wg5OTn6Hay+vr7t27fPmzevqakJRdGuri6VSoVL+0Eikeh0urm5uUgk6tUxEFgEAoHD4TQ0NGg0mqNHj8KO/Kto6dKljx8/xibsBrK2tu7o6KitrZ09e7aNjY1YLAbzysXFxY8fP0ZR1M3N7e23366oqKisrASjCQPTGO3atWvhwoVg0d++ffsuX7783Xff6QeWk5NTWlpaRUUFiqLffPNNZGSkgZ9CsJwVLN2Ji4vDDY9B/2MUCmX58uXp6emPHz82cG/gcrlgkadEIjl+/HhiYmJCQkJiYmJSUtLnn38eHR0dEhJiZ2f35ptvRkZGhoWFmZqaDkxj9OGHHy5atEgul4Md0iEhIRUVFSCfjFAojImJKSoqAoOfMTExzs7O77zzjkwmMxDuCILs3r27ubn55MmTbDYbXwz9D7FYrDNnzoD32Az6zA+MGTNGJpP98MMP3377bUxMDK6UQqGAjj+bzT506JBarTYzMxuY0Q8ElkwmW7169apVq/Ly8m7cuEGn0z08PC5cuFBeXl5YWJieno41++677yqVyi1bthiILQKBIJFIzp07x+Fw8AXQ/5CpqWlCQgLIfwx2ywxEJBKnTZsmlUr9/PwQBBmYe93S0lKhUPD5/D179qjV6ra2NhaLNWhgLViwAAyKdnR0PHv2TCQSMZnMe/furVu3DiyA1k9qyufzW1tbu7u7DTz3GRkZVVZWpqamwsB6tbBYrMTExN7e3vr6ektLy0FXpKxcufLevXsTJkwYKiEWm80GEzLbtm1zc3OTSqUcDmfQwFq8eLFMJps0aRKbzU5OTi4sLGQwGFKpdM2aNfhGdUFjb2/f0tIyaClAIpFgYL2KjIyMHB0dwWqFvLw8bOWxPoFA8Ntvvw11PwOzzt3d3cnJyQwGY8mSJS8NLBC+n376aXl5OYFAaGtr8/HxwTeqA577DOcIkUgkMLBeURYWFqdPnwaxNWHCBFwpn89vaGjQn5PG4fF4KIouWLBg7ty5V69effLkyVB9rIULF3Z1dSUnJ4eHhx84cCA6OvrgwYMHDhx47bXX8I3qWFhYGA6s4ODgjo6OtLQ0+PLfVxSJRLp48eKzZ88yMzPnz5+vX/TSwGIymSKRaMeOHYcPH/75559bW1uH6mMtXLhQJpPduXMHRdG9e/fOnTsXRVED6xQMBBaPx/P399dqtT/88MPf/vY3uIHn1cVkMr/66isURb///ntLS0tTU1Mwov3SwCIQCFZWVmKxODw8fMmSJb/99huHwxl0HGvx4sXt7e2TJ08uLS1NSkpydXVtbm420LKZmdlQgSUUClUqlVwuX7ZsGRx5f9WZmJikpKRoNJqurq7m5maBQIAFluFOjImJSXl5eXh4+Jw5c0AfSyQSKZVKbD2WSqUCww3t7e1cLjcrK0ulUn399dfjxo0b6pmARCKx2ez6+nrwMTBUKnXr1q0qlaqrq8vJyUm/CHp1TZkyJTo6GuwRBQuwBAJBfX29gR8ssEZeIpF88MEHM2bMaG5uNjIysrW1XbBgwbznFi1aRKVSly9f3tbWxmazb9y4UVxcPG3atKGiCixhyM3NVSqVuHfcHz9+XKVS3bt3z93dHd6rhhMulwv68ps2bSIQCIsWLWprazty5Mi+ffuwRcM4DAajoKDg22+/PX36tEKhOHz4cJBOWFjYbp3Q0NC9e/eCtS6xsbFSqRSXSBJn4sSJV56nu3V1dXV0dIyIiPj444+PHTt2WsfT0xN/DvTqo1Ao6enp8+fPd3R0xFIXgcQKgy7YotPp//jHP/7dn9KRyWRisbhUT0FBAZaXOzs7e+3atX6D8fHxAa1pNJqsrCx7e/vQ0FBwVkVFhYODA/7y0HBBJBLBIPgnn3wCulzge+3v779+/frYsWPNzMzMn2Oz2TY2NpcuXVKr1R3P9fX17du3D2TJ0gf6452dnWAIHuxVxOnq6tJoNCBPKVjHFxISgqLogwcPHBwcBh3FhYYZFos1ZsyYadOmdXV1qdXq3t5elUrV1NQklUobn5NKpQ8ePHj//fctLS2xaONyuUN1y0BQWllZjR071noIUVFRPT09nZ2dYKKQRqNxuVw4WDXSkMnkFStWeDyHbeoCPD093d3d/9pUaba2tnw+f8WKFYPuQ4QgQygUCri9DXy4o+rgDkLQH7J8+XKQ8XbJkiW4os2bN3/xxRdDvcEVGlEOHToE3q3KYDDOnDlz7do13NDln7VhwwbwTODl5YUrio+Pv3PnDrxpjXB0Oj0gIODSpUt+fn4gsMBTW3R0NL7qn+Hl5aVUKjUazerVq3FFAoHgzJkzAQEB8KY1ktnb2/f39/v7+4OocnFxkclkTU1NgYGB+KovotPpBmZdDAQWWEHa398Ptw2OZGCXDthX6O7u3tPTo1AoBt0Npo9Go/n7+zc2Ntrb2w869GA4sDZs2CCTyWDSopFMf8Pq6tWrtVqtUql86aRKUFCQSCQSCATXr19fvvxfL6nX5+XlpVKpNBrNwM47gUBYv349DKwRTj+wPDw8nj17plQqB80Rou/s2bO3bt1CEGSovA9eXl4KhUKr1VZUVAxsLSAgAEVRA9u/oGHP2tparVZv3LiRQCC4uro+0xlqPTEmKSmppKTEysqqo6Nj0HXrXl5e4NXRKIp+/vnnuFIXF5fz589v37597NixuCJoJEAQZOHChT/99JO7u7u5ufm2bdt6e3tra2tdXV3xVV904sSJ0tJSS0vLW7duBQYGDtzFpR9Y4D08ODQa7fHjxwMHI6CRgM/nP3r0COw6BCsd2tvbDeytAHPYNBotJSWltLQU5HkvLS2Ni4vDVdMPrCNHjuBKDS9Nhoa9NWvWSKVSsNX4s88+Q1H0999/N5wrAUGQyMhIhUJRUlJCo9EoFIpEIklKSsJVwwZIYWCNRvpr3kHK5Pb2dsMLDVgsVmVl5ffff//GG28YGRkhCFJWVpaYmIirZmtrGxgYCLI5wMAadf4fgcVkMsvLy7HN+AwGY9DAAgvbOzs7YWCNRnw+v76+HmTvOHr06B8MLIlEgnWqDAQWi8UCGWM++eQTfJnuJ7W+vh4G1sgkEAgaGhrs7Ow4HE5SUhIILMPZXQYGlkQiMRxYiYmJ2LQgi8Xi8XhcLtfOzq6hoeE/nOqGXlFr1qxBUfTRo0fV1dUgKW1fXx++0gA//vjj2bNnwd9MJrO2tnZg5x0AP4XNzc3h4eHgyMmTJ3/99df79+8/evQIRdFBx8CgYW/cuHFCoXDnzp27du3atm2bUCjcunVrts6VwWRlZWVmZh4+fBh7TxiZTH777bcTEhIyMzNxlfPz87EHQ5VKlZ+fn5mZGRMTs2PHjg8//HDnzp1CoRC8FQwaFS5cuHDlyhUQXjg5OTkXL16cPn067hQwaYhVy8jIEIlEWVlZZ8+ePaPz5ZdfZmdni0SioVI5QKOOkR4ymWxkZDRwJyqRSARFgLm5+cCxeGi0QBCEx+NZWVlxuVxra2uQe4NIJFpYWHC5XEtLSy6XayD5ggExMTGlpaW2traWekCb+mtsLCwsrKys9N+QCI0EW7duLSsrKykpKS4uvnXrFtaPrqqqunPnTnFxcUlJSX5+vuGB+EHt3bu3t7e3rKysqKio+LmSkpKffvpp2bJlWLXs7OzS0tLy8vLIyMgXzoeGL39//4aGBqxzjaJoTU3NmTNnkpKSAgMDf/nlF3BQo9EYHtbCoVKp27dvr6qq0m8Z88EHH4wZM8bFxeXrr7++fPkydry1tTUtLe3UqVOwLz+M0Wi0wMDAurq6F77z57Rarbe39549e2pqalAUlcvlhoe1cBgMBkiQjPPw4cOEhARvb++NGzd+8803+OLnkpOT582bh28UGhZsbGy6u7vxX6mezs7ON998c+vWrS0tLbdv3x6Y8dYAMpmclJT06NGjOj1NTU2nT5+2tbWVSqUajaa/vx9/ST3YCBk0zIwbNw6MWw5FoVCAN0aTSCQOh8Plcv9gbBGJRNBDxzbjg8dDMpm8du1aw9EMdHd3Hz9+HN8uNCzY2Nj09fXhv9IXaTQaLy8vJyenurq6e/furVy5Et/KYJhMZk1NzcOHDx/oqa+vDwwMdHV1xV9jMGFhYXAh/HBFp9P9/f23bNkSOITNmzeHhobOnDnT2toaJMGaOnUqvpXBUKlUkCtLX3h4+MKFC62srIRCoeGLbtq0CY47QBAEQRAEQRAEQRAEQRAEQRAEQRAEQRAEQRAEQRAEQRAEQRAEQRAEQRAEQRAEQRAEQYP7P/tl7BX0yLavAAAAAElFTkSuQmCCCw==]]></BackgroundImage>
    <ImageOpacity>0.13</ImageOpacity>
    <ImageBlur>0</ImageBlur>
    <Opacity>1</Opacity>
    <MousePassThroughWhileRunning>False</MousePassThroughWhileRunning>
  </Settings>
  <Components>
    <Component>
      <Path>LiveSplit.Title.dll</Path>
      <Settings>
        <Version>1.7.3</Version>
        <ShowGameName>False</ShowGameName>
        <ShowCategoryName>True</ShowCategoryName>
        <ShowAttemptCount>True</ShowAttemptCount>
        <ShowFinishedRunsCount>False</ShowFinishedRunsCount>
        <OverrideTitleFont>True</OverrideTitleFont>
        <OverrideTitleColor>True</OverrideTitleColor>
        <TitleFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAA1Db21pYyBTYW5zIE1TAADAQQX8////GFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQEAAAAHdmFsdWVfXwAIAgAAAAAAAAAF+////xtTeXN0ZW0uRHJhd2luZy5HcmFwaGljc1VuaXQBAAAAB3ZhbHVlX18ACAIAAAACAAAACw==]]></TitleFont>
        <SingleLine>False</SingleLine>
        <TitleColor>DEFFFFFF</TitleColor>
        <BackgroundColor>CC2A2A2A</BackgroundColor>
        <BackgroundColor2>FF131313</BackgroundColor2>
        <BackgroundGradient>Vertical</BackgroundGradient>
        <DisplayGameIcon>False</DisplayGameIcon>
        <ShowRegion>False</ShowRegion>
        <ShowPlatform>False</ShowPlatform>
        <ShowVariables>False</ShowVariables>
        <TextAlignment>1</TextAlignment>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Splits.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <CurrentSplitTopColor>FF3373F4</CurrentSplitTopColor>
        <CurrentSplitBottomColor>FF153574</CurrentSplitBottomColor>
        <VisualSplitCount>8</VisualSplitCount>
        <SplitPreviewCount>1</SplitPreviewCount>
        <DisplayIcons>True</DisplayIcons>
        <ShowThinSeparators>True</ShowThinSeparators>
        <AlwaysShowLastSplit>True</AlwaysShowLastSplit>
        <SplitWidth>20</SplitWidth>
        <SplitTimesAccuracy>Seconds</SplitTimesAccuracy>
        <AutomaticAbbreviations>False</AutomaticAbbreviations>
        <BeforeNamesColor>FFFFFFFF</BeforeNamesColor>
        <CurrentNamesColor>FFFFFFFF</CurrentNamesColor>
        <AfterNamesColor>FFFFFFFF</AfterNamesColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BeforeTimesColor>FFFFFFFF</BeforeTimesColor>
        <CurrentTimesColor>FFFFFFFF</CurrentTimesColor>
        <AfterTimesColor>FFFFFFFF</AfterTimesColor>
        <OverrideTimesColor>False</OverrideTimesColor>
        <ShowBlankSplits>True</ShowBlankSplits>
        <LockLastSplit>True</LockLastSplit>
        <IconSize>24</IconSize>
        <IconShadows>True</IconShadows>
        <SplitHeight>0</SplitHeight>
        <CurrentSplitGradient>Vertical</CurrentSplitGradient>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>01FFFFFF</BackgroundColor2>
        <BackgroundGradient>Alternating</BackgroundGradient>
        <SeparatorLastSplit>True</SeparatorLastSplit>
        <DeltasAccuracy>Tenths</DeltasAccuracy>
        <DropDecimals>True</DropDecimals>
        <OverrideDeltasColor>False</OverrideDeltasColor>
        <DeltasColor>FFFFFFFF</DeltasColor>
        <Display2Rows>False</Display2Rows>
        <ShowColumnLabels>False</ShowColumnLabels>
        <LabelsColor>FFFFFFFF</LabelsColor>
        <Columns>
          <Settings>
            <Version>1.5</Version>
            <Name>+/-</Name>
            <Type>Delta</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Current Timing Method</TimingMethod>
          </Settings>
          <Settings>
            <Version>1.5</Version>
            <Name>Time</Name>
            <Type>SplitTime</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Current Timing Method</TimingMethod>
          </Settings>
        </Columns>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.Timer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <TimerHeight>39</TimerHeight>
        <TimerWidth>225</TimerWidth>
        <TimerFormat>1.23</TimerFormat>
        <OverrideSplitColors>False</OverrideSplitColors>
        <ShowGradient>True</ShowGradient>
        <TimerColor>FFAAAAAA</TimerColor>
        <BackgroundColor>00000000</BackgroundColor>
        <BackgroundColor2>4BFF0000</BackgroundColor2>
        <BackgroundGradient>Horizontal</BackgroundGradient>
        <CenterTimer>False</CenterTimer>
        <TimingMethod>Current Timing Method</TimingMethod>
        <DecimalsSize>35</DecimalsSize>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.PreviousSegment.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BackgroundColor>00000000</BackgroundColor>
        <BackgroundColor2>FF0D0D0D</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <DeltaAccuracy>Tenths</DeltaAccuracy>
        <DropDecimals>False</DropDecimals>
        <Comparison>Current Comparison</Comparison>
        <Display2Rows>False</Display2Rows>
        <ShowPossibleTimeSave>False</ShowPossibleTimeSave>
        <TimeSaveAccuracy>Tenths</TimeSaveAccuracy>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.RunPrediction.dll</Path>
      <Settings>
        <Version>1.4</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FFFFFFFF</TimeColor>
        <OverrideTimeColor>False</OverrideTimeColor>
        <Accuracy>Seconds</Accuracy>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Comparison>Best Segments</Comparison>
        <Display2Rows>True</Display2Rows>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.BlankSpace.dll</Path>
      <Settings>
        <Version>1.7</Version>
        <SpaceHeight>1</SpaceHeight>
        <SpaceWidth>100</SpaceWidth>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Counter.dll</Path>
      <Settings>
        <Version>1.0</Version>
        <GlobalHotkeysEnabled>True</GlobalHotkeysEnabled>
        <OverrideCounterFont>True</OverrideCounterFont>
        <OverrideTextColor>True</OverrideTextColor>
        <CounterFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAABJEZXRlcm1pbmF0aW9uIE1vbm8AANBBBfz///8YU3lzdGVtLkRyYXdpbmcuRm9udFN0eWxlAQAAAAd2YWx1ZV9fAAgCAAAAAAAAAAX7////G1N5c3RlbS5EcmF3aW5nLkdyYXBoaWNzVW5pdAEAAAAHdmFsdWVfXwAIAgAAAAIAAAAL]]></CounterFont>
        <CounterTextColor>FFFE1F1F</CounterTextColor>
        <CounterValueColor>FFFE1F1F</CounterValueColor>
        <BackgroundColor>00010000</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <CounterText>KILLS</CounterText>
        <InitialValue>0</InitialValue>
        <Increment>1</Increment>
        <IncrementKey>Add</IncrementKey>
        <DecrementKey>Subtract</DecrementKey>
        <ResetKey>Decimal</ResetKey>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Sound.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <Split>
        </Split>
        <SplitAheadGaining>
        </SplitAheadGaining>
        <SplitAheadLosing>
        </SplitAheadLosing>
        <SplitBehindGaining>
        </SplitBehindGaining>
        <SplitBehindLosing>
        </SplitBehindLosing>
        <BestSegment>
        </BestSegment>
        <UndoSplit>
        </UndoSplit>
        <SkipSplit>
        </SkipSplit>
        <PersonalBest>
        </PersonalBest>
        <NotAPersonalBest>
        </NotAPersonalBest>
        <Reset>E:\CurrentWkDir\Assets\VldWandSndEffect\MarvelRivals\Again.wav</Reset>
        <Pause>
        </Pause>
        <Resume>
        </Resume>
        <StartTimer>E:\CurrentWkDir\Assets\VldWandSndEffect\MarvelRivals\Armed and Dangerous.wav</StartTimer>
        <OutputDevice>0</OutputDevice>
        <SplitVolume>100</SplitVolume>
        <SplitAheadGainingVolume>100</SplitAheadGainingVolume>
        <SplitAheadLosingVolume>100</SplitAheadLosingVolume>
        <SplitBehindGainingVolume>100</SplitBehindGainingVolume>
        <SplitBehindLosingVolume>100</SplitBehindLosingVolume>
        <BestSegmentVolume>100</BestSegmentVolume>
        <UndoSplitVolume>100</UndoSplitVolume>
        <SkipSplitVolume>100</SkipSplitVolume>
        <PersonalBestVolume>100</PersonalBestVolume>
        <NotAPersonalBestVolume>100</NotAPersonalBestVolume>
        <ResetVolume>100</ResetVolume>
        <PauseVolume>100</PauseVolume>
        <ResumeVolume>100</ResumeVolume>
        <StartTimerVolume>100</StartTimerVolume>
        <GeneralVolume>100</GeneralVolume>
      </Settings>
    </Component>
  </Components>
</Layout>